name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test-bitnest:
    name: 'Test bitnest'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install .[dev]
          sudo apt install graphviz -y
      - name: Black Formatting
        run: |
          black --version
          black bitnest tests models --diff
          black --check bitnest tests models
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8
      - name: Run tests
        run: |
          pytest

  docs-bitnest:
    name: 'Sphinx docs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: |
          pip install .[dev]
      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build
